name: mma_2024 # adds FMA dependencies 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  
  - pip
  - pip:
    # Base dependencies
    - wget
    - plotly==5.20.0
    - dash==2.16.1
    - dash-bootstrap-components
    - dash-ag-grid
    - wordcloud
    - dash-image-gallery
    - dash-core-components
    - dash-holoniq-wordcloud
    
    # Audio Processing dependencies
    - torch
    - torchaudio
    - shazamio
    - jupyter
    - numpy
    - matplotlib
    - librosa
    - tqdm
    - python-dotenv
    - pandas
    - scikit-learn
    - umap-learn
    - setuptools<70.0.0 # There's a change with setuptools which makes the latest version incompatible with CLIP for the time being
    - pytorch-lightning
    - transformers