name: mma_2024
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  
  - pandas
  - scikit-learn
  - umap-learn
  - pip
  - pip:
    - wget
    - plotly==5.20.0
    - dash==2.16.1
    - torch
    - dash-bootstrap-components
    - dash-ag-grid
    - wordcloud
    - dash-image-gallery
    - dash-core-components
    - dash-holoniq-wordcloud
    - git+https://github.com/openai/CLIP.git
    - setuptools<70.0.0 # There's a change with setuptools which makes the latest version incompatible with CLIP for the time being
    - pydub #convert mp3 to wav
